
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String arg[]) {
		System.out.println("Here is the Kim.");
		System.out.println("also change the output.");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}

